spring:
  application:
    name: communications-bffe

  datasource:
    url: jdbc:postgresql://workwise-db:5432/workwise
    username: sichiarelli
    password: '@Linux110'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Puoi configurare l'aggiornamento automatico del database se necessario

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://my-auth-server.com

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

swagger-ui:
  path: /custom/swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: mappings

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: YourSignInKey
  authorities:
    key: roles
  header:
    string: Authorization

